import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  await prisma.offer.deleteMany();

  await prisma.offer.createMany({
    data: [
      {
        title: "HDFC Personal Loan",
        category: "personal_loan",
        dsaName: "HDFC Bank",
        description: "Instant personal loan for salaried",
        interestRate: "10.5% - 14%",
        benefits: "Quick disbursal, minimal docs",
        redirectUrl: "https://example.com",
        status: "active",
        priority: 1,
        minCreditScore: 700,
        minMonthlyIncome: 25000,
        employmentTypes: JSON.stringify([
          "salaried_govt",
          "salaried_private",
          "salaried_mnc",
        ]),
        minLoanAmount: 50000,
        maxLoanAmount: 4000000,
        minInterestRate: 10.5,
        maxInterestRate: 14.0,
        isFeatured: true,
        badgeText: "Top Pick",
      },
      {
        title: "Bajaj Finserv Personal Loan",
        category: "personal_loan",
        dsaName: "Bajaj Finserv",
        description: "Personal loan for all profiles",
        interestRate: "13% - 24%",
        benefits: "NTC friendly, fast approval",
        redirectUrl: "https://example.com",
        status: "active",
        priority: 2,
        minCreditScore: 650,
        minMonthlyIncome: 15000,
        employmentTypes: JSON.stringify([]),
        allowNTCUsers: true,
        isNewToCreditFriendly: true,
        minLoanAmount: 30000,
        maxLoanAmount: 2500000,
        minInterestRate: 13.0,
        maxInterestRate: 24.0,
        badgeText: "NTC Friendly",
      },
      {
        title: "Axis Bank Personal Loan",
        category: "personal_loan",
        dsaName: "Axis Bank",
        description: "Premium loan for high scorers",
        interestRate: "9.9% - 12%",
        benefits: "Lowest rates for 750+ score",
        redirectUrl: "https://example.com",
        status: "active",
        priority: 1,
        minCreditScore: 750,
        minMonthlyIncome: 40000,
        employmentTypes: JSON.stringify(["salaried_mnc", "salaried_private"]),
        employerCategories: JSON.stringify(["mnc", "listed_private", "govt"]),
        minLoanAmount: 100000,
        maxLoanAmount: 5000000,
        minInterestRate: 9.9,
        maxInterestRate: 12.0,
        isFeatured: true,
        badgeText: "Pre-Approved Eligible",
      },
      {
        title: "Tata Capital Home Loan",
        category: "home_loan",
        dsaName: "Tata Capital",
        description: "Home loans at competitive rates",
        interestRate: "8.5% - 10%",
        benefits: "Long tenure, low EMI",
        redirectUrl: "https://example.com",
        status: "active",
        priority: 2,
        minCreditScore: 680,
        minMonthlyIncome: 35000,
        employmentTypes: JSON.stringify([]),
        minLoanAmount: 1000000,
        maxLoanAmount: 50000000,
        minTenureMonths: 60,
        maxTenureMonths: 360,
        minInterestRate: 8.5,
        maxInterestRate: 10.0,
        isSecured: true,
        collateralType: "property",
      },
      {
        title: "SBI Credit Card",
        category: "credit_card",
        dsaName: "SBI Card",
        description: "Entry level credit card",
        interestRate: "3.5% monthly",
        benefits: "Rewards on every spend",
        redirectUrl: "https://example.com",
        status: "active",
        priority: 3,
        minCreditScore: 700,
        minMonthlyIncome: 20000,
        employmentTypes: JSON.stringify([
          "salaried_govt",
          "salaried_private",
          "salaried_mnc",
        ]),
        maxExistingCreditCards: 3,
        minInterestRate: 36.0,
        maxInterestRate: 42.0,
      },
      {
        title: "MoneyView Personal Loan",
        category: "personal_loan",
        dsaName: "MoneyView",
        description: "Loan for moderate credit profiles",
        interestRate: "16% - 36%",
        benefits: "Lower score accepted",
        redirectUrl: "https://example.com",
        status: "active",
        priority: 4,
        minCreditScore: 600,
        minMonthlyIncome: 13500,
        employmentTypes: JSON.stringify([]),
        allowNTCUsers: false,
        minLoanAmount: 10000,
        maxLoanAmount: 500000,
        minInterestRate: 16.0,
        maxInterestRate: 36.0,
      },
    ],
  });

  console.log("Seeded 6 test offers successfully");
  await prisma.$disconnect();
}

main().catch(console.error);
